// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:school_surveys/data/database/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SurveyAdapter());
    registerAdapter(SurveyStatusAdapter());
    registerAdapter(UserAdapter());
  }
}
